### ISSUE TITLE
Method Error after package update

### ISSUE THREAD

**Issue by JulesBlubb** [SciML/DifferentialEquations.jl#659] opened 2020-08-27 10:44 UTC
Hi, 
I am getting an error after updating Differential Equations package. It says:
no method matching iterate(::DataStructures.BinaryHeap{Float64,DataStructures.LessThan)

My example code is:
```julia

using DifferentialEquations

function ODESolver(a)
    p = a
    function lotka_volterra(du,u,p,t)
        x, y = u
        du[1] = dx = 1.0*x^a - 1.0*x*y
        du[2] = dy = -2.0*y + 1.0*x*y
    end
    u0 = [1.0,1.0]
    tspan = (0.0,10.0)
    prob = ODEProblem(lotka_volterra,u0,tspan,p)
    sol = solve(prob)
    return(sol)
end

function comb_a()
        for y in 1:3
            a = y
            dat = ODESolver(a)
        end
end

comb_a()
```

It worked before the update without problems. I hope you can help me. Thanks a lot.

**Comment by MMHoogesteger** [comment] 2020-08-27 21:29
After struggling with this for a day or two and not progressing, nor finding any issues about it, I just decided to post about this myself: https://github.com/SciML/DiffEqBase.jl/issues/575#issue-687552430 Now I see yours. Maybe one of them can be closed :)

**Comment by ChrisRackauckas** [comment] 2020-08-27 21:32
@oxinabox @DhairyaLGandhi @maleadt

**Comment by ChrisRackauckas** [comment] 2020-08-27 21:39
The issue is that some packages in the ecosystem are holding back DataStructures.jl v0.18. @devmotion has been fixing this up, but it's all of the packages outside of SciML that need to go update so we need to go hound and ping everyone until they fix their stuff.

**Comment by devmotion** [comment] 2020-08-27 23:53
The compatibility issue should be fixed by https://github.com/SciML/DiffEqBase.jl/pull/576 and https://github.com/JuliaRegistries/General/pull/20415#event-3701760120 and (from our side at least).

**Closed by devmotion** 2020-08-27 23:53 UTC
