### ISSUE TITLE
Integrator stepped past tstops but the algorithm was dtchangeable

### ISSUE THREAD

**Issue by Janssena** [SciML/DifferentialEquations.jl#747] opened 2021-05-03 12:57 UTC
Hey All, 

I found a scenario where the following error occurred:
`ERROR: Something went wrong. Integrator stepped past tstops but the algorithm was dtchangeable. Please report this error.`

MWE:

```julia
function de(du, u, p, t) # specific DE does not impact the issue
           a, b = p
           du[1] = a * u[1]
           du[2] = b * u[2]
end

saveat = [0.0, 0.0094777, 1.5574]
tstop = 0.010823

affect!(integrator) = integrator.u[1] += 1.0
condition(u, t, integrator) = t == tstop
callback = diffeq.DiscreteCallback(condition, affect!)

prob = ODEProblem(de, zeros(2), (-1, 3.), rand(2))
sol = solve(prob, saveat=saveat, tstops=tstop, callback=callback)
```

I'm guessing it is because the tstop is close to one of the saveat timepoints?

**Comment by ChrisRackauckas** [comment] 2021-05-09 05:54
Fixed by https://github.com/SciML/OrdinaryDiffEq.jl/pull/1401. It is indeed a floating point issue caused by `(t + dt) - dt > 10eps(dt)`, which probably needs a slight bump.

**Closed** 2021-05-09 20:03 UTC
