### ISSUE TITLE
Non-deterministic unstable-ish Tsit5 solution 

### ISSUE THREAD

**Issue by louisponet** [SciML/DifferentialEquations.jl#636] opened 2020-07-14 21:49 UTC
With the following code, I run into a changing solution when using `Tsit5()` as-is:
```julia
using DifferentialEquations
const Tc = 290.0
const T_environment = 112.0

params = (α   = 6038.988133496954,
          flr = 0.9143297159342292,
          βc = 3.3756166296365625e8,
          Cb = 3.575738493809821,
          γl = 25.0,
          Ci = 0.5225152858521894,
          fl = 64.43101648478608,
          γs = 0.755292483075266,
          k = 1.291134813762553,
          β = 7.96563074782321e7,
          ξ = 0.07453198587254402,
          ω = 14.107763776066768,
          Cs = 0.3585741268086582,
          t1 = 0.09720822150517766,
          t2 = 0.3893752124241148)
          
fv(dv, v, u, p, t) = 
	dv[1] = p[:Ci] * L0(u[2], p, u[1])^2 - p[:ω]^2 * u[1] - p[:γs] * v[1] - p[:βc] * u[1]^3
function fu(Qfunc, du, v, u, p, t)
	Qt  = Qfunc(t)
	TL  = u[2]
	Tb  = u[3]
	Tr    = TL - Tb
	Tcr   = Tc - Tb
	du[1] = v[1]
	du[2] = 1 / p[:Cs] * (- p[:k] * Tr + Qt)
	du[3] = 1 / p[:Cb]  * (1 * p[:k] * Tr)
end

function L0(T, ω, α, β, Ci, y)
    L2 = (-α*(T-Tc) + 2 * Ci * y) / β
    L2 < 0.0 ? 0.0 : sqrt(L2)
end
function y0(T, ω, α, β, Ci, βc)
	b1 = -9 * α * βc^2 * Ci * (T-Tc) / β
	b2 = sqrt(3) * sqrt((27*α^2 * β * βc^4* Ci^2*(T-Tc)^2 - 4*(2*βc*Ci^2-β*βc*ω^2)^3)/β^3)

	return (2*3^(1/3) * βc * (2*Ci^2 - β * ω^2) + 2^(1/3) * β * (b1 + b2)^(2/3))/(6^(2/3) * β * βc *(b1+b2)^(1/3))
end

L0(T, p, args...) = L0(T, p[:ω], p[:α], p[:β], p[:Ci], y0(T, p))
y0(T, p) = y0(T, p[:ω], p[:α], p[:β], p[:Ci], p[:βc])

Qfunc(p) =
    t -> p.fl/(p.ξ*√π) * (exp(-0.5*((t - p.t1) /p.ξ)^2) + p.flr*exp(-0.5*((t - p.t2) /p.ξ)^2))

prob = DynamicalODEProblem(fv, (a, b, c, d, e) -> fu(Qfunc(params), a, b, c, d, e), [0.0,0.0,0.0], [y0(T_environment, params), T_environment, T_environment], (-3.61595,9.984), params)

sol = solve(prob, Tsit5())
t = getindex.(sol.(range(-2,8,length=300)), 5)
strange = 0
for i = 1:1000
    s = solve(prob, Tsit5())
    if getindex.(s.(range(-2,8,length=300)), 5) != t
        global strange += 1
    end
end
strange
```
The culprit largely seems to come from the very sharp gaussians that inject heat (`Qfunc`) into the system.
If I require reltol and abstol to be smaller than what the defaults are, things seem to be working better. The real strange thing though is the non deterministic behavior.

**Comment by ChrisRackauckas** [comment] 2020-07-14 23:38
@utkarsh530 @kanav99 could I get another pair of 👀 ?

**Comment by utkarsh530** [comment] 2020-07-15 19:28
Yeah, I will try to find the cause.

**Comment by jonasmac16** [comment] 2020-08-03 15:04
I have a similar issue in terms of non-deterministic solutions when using AutoVern9(Rodas4()) which goes away if you only use Rodas4(). I will put together a MWE to demonstrate it as soon as I have a minute.

**Comment by ChrisRackauckas** [comment] 2020-08-03 20:29
Maybe there's an uninitialized cache somewhere?

**Comment by dcabecinhas** [comment] 2020-08-08 11:30
@louisponet I've had a similar situation happen and it was due to the derivatives not being all assigned in f(). 

Seems to be the case in you problem definition. Setting either `dv[2] = 0, dv[3] = 0` in fv() or giving the initial condition `v0 = [0.0]` in the problem makes the non-deterministic behavior go away.

**Comment by ChrisRackauckas** [comment] 2020-08-09 15:37
https://github.com/SciML/OrdinaryDiffEq.jl/pull/1236 should help

**Comment by ChrisRackauckas** [comment] 2020-08-09 15:39
Yes, the issue seems to come from relying on zero'd uninitialized memory, which should be fixed by never using `similar`.

**Comment by louisponet** [comment] 2020-08-12 17:28
Cool, thanks for the heads up guys! Great work!

**Comment by dcabecinhas** [comment] 2020-08-13 12:51
@ChrisRackauckas There is still some problem with uninitialized memory. Even with this last PR one cannot trust dx to be initialized with zeros. u0 with 1000 elements is usually enough to make some 'NaNs' appear on my system.

```julia
using OrdinaryDiffEq

function f!(du,u,p,t) 
#  du .= -1.01*u
end
tspan = (0.0,10.0)

u0 = rand(1000)
prob = ODEProblem(f!,u0,tspan)
sol = solve(prob,Tsit5())

u0 = rand(1000)
prob = ODEProblem(f!,u0,tspan)
sol = solve(prob,Tsit5())
# ┌ Warning: Automatic dt set the starting dt as NaN, causing instability.
# └ @ OrdinaryDiffEq ~/.julia/packages/OrdinaryDiffEq/C72aU/src/solve.jl:459
# ┌ Warning: NaN dt detected. Likely a NaN value in the state, parameters, or derivative value caused this outcome.
# └ @ DiffEqBase ~/.julia/packages/DiffEqBase/dKNbf/src/integrator_interface.jl:323
# retcode: DtNaN
# Interpolation: specialized 4th order "free" interpolation
# t: 1-element Array{Float64,1}:
#  0.0
# ...
```

```
pkg> st
Status
  [459566f4] DiffEqCallbacks v2.13.5
  [0c46a032] DifferentialEquations v6.15.0
  [1dea7af3] OrdinaryDiffEq v5.42.2
  [789caeaf] StochasticDiffEq v6.25.0
```

**Comment by ChrisRackauckas** [comment] 2020-08-16 02:23
@utkarsh530 could you see if you can find any un-zero'd memory that is a problem here?

**Comment by utkarsh530** [comment] 2020-08-16 15:01
Yeah, let me check particularly in `Tsit5()` if we are missing something.

**Comment by ChrisRackauckas** [comment] 2022-08-05 15:25
This was fixed but the issue wasn't closed!

**Closed by ChrisRackauckas** 2022-08-05 15:25 UTC
