### ISSUE TITLE
How to solve stiff Neural ODE with many params (> 2000)?

### ISSUE THREAD

**Issue by LibinXu** [SciML/DifferentialEquations.jl#810] opened 2021-10-20 01:39 UTC
```julia
​using Flux, DifferentialEquations, DiffEqSensitivityusing LinearAlgebra
using ForwardDiff​

const N = 39​

model = Chain(Dense(2 * (N+1), 20, tanh), 
                         Dense(20, N), x -> leakyrelu.(x + collect(Float32, 1:N)))
p, re = Flux.destructure(model)
ps = Flux.params(p)​

##
A = diagm(0 => -collect(Float32, 0.0:N), 1 => collect(Float32, 1.0:N))
function ODE(du, u, p, t)
    Dt = 20
    vec = re(p)(u)
    mat = diagm(0 => [-vec; 0.0], -1 => vec) 
    G = (A + mat) * Dt
    du[1:N+1] = G * u[1:N+1]
    du[N+2:end] = G * u[N+2:end]
end​

u0 = repeat([1.0f0; zeros(Float32, N)], 2)
prob = ODEProblem(ODE, u0, (0.0f0, 20f0), ps[1])​

alg = Tsit5()
sol = Array(solve(prob, alg, u0=u0, p=p, saveat=0.0:0.1:20.0))​

function loss()
    sol = Array(solve(prob, alg, u0=u0, p=p, saveat=0.0:0.1:20.0))
    return Flux.mse(sol, rand(80, 201))end​@time Flux.train!(loss, ps, Iterators.repeated((), 1), ADAM())
```

This is my training code. When variable `Dt=2`, it takes about 20s to train for each epoch, but about 120s when `Dt=20`. However, the maximum of `Dt` is 100 at my problem. 

The main issue is when `Dt` gets larger the ODE gets stiffer, and I stiff use `Tsit5()` to solve the ODE. I have tried to use other solvers that can solve stiff ODE such as `Rosenbrock23()`, but I get the `MethodError` bug: 
```julia
MethodError: ReverseDiff.TrackedReal{ForwardDiff.Dual{ForwardDiff.Tag{SciMLBase.TimeGradientWrapper{ODEFunction{true, DiffEqSensitivity.ODEInterpolatingAdjointSensitivityFunction{DiffEqSensitivity.AdjointDiffCache{Nothing,......Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing}, Vector{Float32}, Vector{Float32}}, Float32}, Float32, 1}) is ambiguous.
```

And I know it can calculate the gradient if I use `ForwardDiff.jl`, but it still takes too much time. Is there some good ways to go?

**Comment by ChrisRackauckas** [comment] 2021-10-20 01:46
See https://aip.scitation.org/doi/10.1063/5.0060697 for details.

Tsit5 is a bad idea. For Rosenbrock here you need to pass `tgrad = (du,u,p,t) -> du .= false` to the `ODEFunction` to specialize the time gradient (since you know it's zero). But you're probably better off just using TRBDF2 or QNDF given the size of the adjoint.

Then, at this size you probably need to be using QuadratureAdjoint (for the reasons mentioned in the paper). But remember, `QuadratureAdjoint(;abstol=1e-6,reltol=1e-3,compile=false,ADKwargs...)`: remember to set the quadrature's tolerances low enough. 

Lastly, you should try and make sure your RHS is compatible with ReverseDiff compilation or Enzyme. Compiling the vjp is more than an order of magnitude improvement.

**Comment by ChrisRackauckas** [comment] 2021-11-01 22:57
We changed the defaults of QuadratureAdjoint to match the ODE solver tolerances, so that part should be fine now. Note that `abstol=1e-20, reltol=1e-18` is a bad idea since the relative tolerance of of Float64 is only 1e-16, so you'll have a very hard time getting that to 1e-18!. 

>Can I just ignore this warning?

Yes you can. @chriselrod can we make that fallback not noisy? The issue is that it's on TrackedReal.

**Comment by ChrisRackauckas** [comment] 2021-11-01 22:58
Runnable version of the example:

```julia
using Flux, DifferentialEquations, DiffEqSensitivity
using LinearAlgebra
using ForwardDiff
const N = 39

model = Chain(Dense(2 * (N+1), 20, tanh),
                         Dense(20, N), x -> leakyrelu.(x + collect(Float32, 1:N)))
p, re = Flux.destructure(model)
ps = Flux.params(p)

##
A = diagm(0 => -collect(Float32, 0.0:N), 1 => collect(Float32, 1.0:N))
function ODE(du, u, p, t)
    Dt = 20
    vec = re(p)(u)
    mat = diagm(0 => [-vec; 0.0], -1 => vec)
    G = (A + mat) * Dt
    du[1:N+1] = G * u[1:N+1]
    du[N+2:end] = G * u[N+2:end]
end

u0 = repeat([1.0f0; zeros(Float32, N)], 2)
prob = ODEProblem(ODE, u0, (0.0f0, 20f0), ps[1])
alg = Tsit5()
sol = Array(solve(prob, alg, u0=u0, p=p, saveat=0.0:0.1:20.0))

alg = TRBDF2(autodiff=false);
sense = QuadratureAdjoint(;abstol=1e-20, reltol=1e-18, compile=false);
tsteps = 0:0.1:20.0

function loss_adjoint(p, problem, u0)
    sol = Array(solve(problem, alg, u0=u0, p=p, saveat=tsteps, sensalg=sense))
    return sum(sol)
end

opt = ADAM(0.1)
@time grad = ForwardDiff.gradient(x -> loss_adjoint(x, prob, u0), ps[1])
```

**Comment by ChrisRackauckas** [comment] 2021-11-01 23:16
Oh, the grad check was using ForwardDiff, that's why its timing wasn't using the sensealg... Better test version:

```julia
using Flux, DifferentialEquations, DiffEqSensitivity
using LinearAlgebra
using ForwardDiff, Zygote
const N = 39

model = Chain(Dense(2 * (N+1), 20, tanh),
                         Dense(20, N), x -> leakyrelu.(x + collect(Float32, 1:N)))
p, re = Flux.destructure(model)
ps = Flux.params(p)

##
A = diagm(0 => -collect(Float32, 0.0:N), 1 => collect(Float32, 1.0:N))
function ODE(du, u, p, t)
    Dt = 20
    vec = re(p)(u)
    mat = diagm(0 => [-vec; 0.0], -1 => vec)
    G = (A + mat) * Dt
    du[1:N+1] = G * u[1:N+1]
    du[N+2:end] = G * u[N+2:end]
end

u0 = repeat([1.0f0; zeros(Float32, N)], 2)
prob = ODEProblem(ODE, u0, (0.0f0, 20f0), ps[1])
alg = Tsit5()
sol = Array(solve(prob, alg, u0=u0, p=p, saveat=0.0:0.1:20.0))

alg = TRBDF2(autodiff=false);
sense = QuadratureAdjoint(autojacvec=ReverseDiffVJP(true),compile=true)
tsteps = 0:0.1:20.0

function loss_adjoint(p, problem, u0)
    sol = Array(solve(problem, alg, u0=u0, p=p, saveat=tsteps, sensealg=sense))
    return sum(sol)
end

opt = ADAM(0.1)
@time grad = Zygote.gradient(x -> loss_adjoint(x, prob, u0), ps[1])
```

EnzymeVJP segfaults, but that's probably because the `f` function allocates and I know that isn't all handled yet (@wsmoses). ReverseDiff is funny...

```julia
MethodError: (::ReverseDiff.ForwardOptimize{typeof(+)})(::ReverseDiff.TrackedReal{Float64, Float64, Nothing}, ::ReverseDiff.TrackedReal{Float32, Float32, ReverseDiff.TrackedArray{Float32, Float32, 1, Vector{Float32}, Vector{Float32}}}) is ambiguous. Candidates:
  (self::ReverseDiff.ForwardOptimize{F})(t::ReverseDiff.TrackedReal{V, D, O} where O, x::Real) where {F, V, D} in ReverseDiff at C:\Users\accou\.julia\packages\ReverseDiff\OciDO\src\macros.jl:121
  (self::ReverseDiff.ForwardOptimize{F})(x::Real, t::ReverseDiff.TrackedReal{V, D, O} where O) where {F, V, D} in ReverseDiff at C:\Users\accou\.julia\packages\ReverseDiff\OciDO\src\macros.jl:109
Possible fix, define
  (::ReverseDiff.ForwardOptimize{F})(::ReverseDiff.TrackedReal{V, D, O} where O, ::ReverseDiff.TrackedReal{V, D, O} where O) where {F, V, D, V, D}
+(a::ReverseDiff.TrackedReal{Float64, Float64, Nothing}, b::ReverseDiff.TrackedReal{Float32, Float32, ReverseDiff.TrackedArray{Float32, Float32, 1, Vector{Float32}, Vector{Float32}}}) at scalars.jl:9
_diagm(::Nothing, ::Pair{Int64, ReverseDiff.TrackedArray{Float64, Float64, 1, Vector{Float64}, Vector{Float64}}}, ::Vararg{Pair{var"#s832", var"#s831"} where {var"#s832"<:Integer, var"#s831"<:(AbstractVector{T} where T)}, N} where N) at dense.jl:286
diagm(::Pair{Int64, ReverseDiff.TrackedArray{Float64, Float64, 1, Vector{Float64}, Vector{Float64}}}, ::Pair{Int64, ReverseDiff.TrackedArray{Float32, Float32, 1, Vector{Float32}, Vector{Float32}}}) at dense.jl:279
ODE(du::Vector{ReverseDiff.TrackedReal{Float32, Float32, ReverseDiff.TrackedArray{Float32, Float32, 1, Vector{Float32}, Vector{Float32}}}}, u::ReverseDiff.TrackedArray{Float32, Float32, 1, Vector{Float32}, Vector{Float32}}, p::ReverseDiff.TrackedArray{Float32, Float32, 1, Vector{Float32}, Vector{Float32}}, t::ReverseDiff.TrackedReal{Float32, Float32, ReverseDiff.TrackedArray{Float32, Float32, 1, Vector{Float32}, Vector{Float32}}}) at test.jl:16
ODEFunction at scimlfunctions.jl:334 [inlined]
(::DiffEqSensitivity.var"#110#125"{ODEFunction{true, typeof(ODE), UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing}})(u::ReverseDiff.TrackedArray{Float32, Float32, 1, Vector{Float32}, Vector{Float32}}, p::ReverseDiff.TrackedArray{Float32, Float32, 1, Vector{Float32}, Vector{Float32}}, t::ReverseDiff.TrackedArray{Float32, Float32, 1, Vector{Float32}, Vector{Float32}}) at adjoint_common.jl:146
ReverseDiff.GradientTape(f::Function, input::Tuple{Vector{Float32}, Vector{Float32}, Vector{Float32}}, cfg::ReverseDiff.GradientConfig{Tuple{ReverseDiff.TrackedArray{Float32, Float32, 1, Vector{Float32}, Vector{Float32}}, ReverseDiff.TrackedArray{Float32, Float32, 1, Vector{Float32}, Vector{Float32}}, ReverseDiff.TrackedArray{Float32, Float32, 1, Vector{Float32}, Vector{Float32}}}}) at tape.jl:207
ReverseDiff.GradientTape(f::Function, input::Tuple{Vector{Float32}, Vector{Float32}, Vector{Float32}}) at tape.jl:204
adjointdiffcache(g::DiffEqSensitivity.var"#df#235"{FillArrays.Fill{Float64, 2, Tuple{Base.OneTo{Int64}, Base.OneTo{Int64}}}, Colon}, sensealg::QuadratureAdjoint{0, true, Val{:central}, ReverseDiffVJP{false}}, discrete::Bool, sol::ODESolution{Float32, 2, Vector{Vector{Float32}}, Nothing, Nothing, Vector{Float32}, Vector{Vector{Vector{Float32}}}, ODEProblem{Vector{Float32}, Tuple{Float32, Float32}, true, Vector{Float32}, ODEFunction{true, typeof(ODE), UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing}, Base.Iterators.Pairs{Union{}, Union{}, Tuple{}, NamedTuple{(), Tuple{}}}, SciMLBase.StandardODEProblem}, TRBDF2{12, false, DefaultLinSolve, NLNewton{Rational{Int64}, Rational{Int64}, Rational{Int64}}, Val{:forward}}, OrdinaryDiffEq.InterpolationData{ODEFunction{true, typeof(ODE), UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing}, Vector{Vector{Float32}}, Vector{Float32}, Vector{Vector{Vector{Float32}}}, OrdinaryDiffEq.TRBDF2Cache{Vector{Float32}, Vector{Float32}, Vector{Float32}, OrdinaryDiffEq.TRBDF2Tableau{Float32, Float32}, OrdinaryDiffEq.NLSolver{NLNewton{Rational{Int64}, Rational{Int64}, Rational{Int64}}, true, Vector{Float32}, Float32, Nothing, Float32, OrdinaryDiffEq.NLNewtonCache{Vector{Float32}, Float32, Float32, Vector{Float32}, Matrix{Float32}, Matrix{Float32}, SciMLBase.UJacobianWrapper{ODEFunction{true, typeof(ODE), UniformScaling{Bool}, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, Nothing, typeof(SciMLBase.DEFAULT_OBSERVED), Nothing}, Float32, Vector{Float32}}, FiniteDiff.JacobianCache{Vector{Float32}, Vector{Float32}, Vector{Float32}, UnitRange{Int64}, Nothing, Val{:forward}(), Float32}, DefaultLinSolve}}}}, DiffEqBase.DEStats}, dg::Not...
```

@mohamed82008 is it as easy as adding the method of both tracked or is that dangerous?

**Comment by chriselrod** [comment] 2021-11-02 06:14
> Yes you can. @chriselrod can we make that fallback not noisy? The issue is that it's on TrackedReal.

`@turbo warn_check_args=false ...`

**Comment by mohamed82008** [comment] 2021-11-02 07:22
> @mohamed82008 is it as easy as adding the method of both tracked or is that dangerous?

I will look into it.

**Comment by mohamed82008** [comment] 2021-11-03 07:33
@ChrisRackauckas the error goes away if you change `0.0` to `0.0f0` in `diagm`.

**Comment by ChrisRackauckas** [comment] 2021-11-03 16:57
Cool, that means:

```julia
using Flux, DifferentialEquations, DiffEqSensitivity
using LinearAlgebra
using ForwardDiff, Zygote
const N = 39

model = Chain(Dense(2 * (N+1), 20, tanh),
                         Dense(20, N), x -> leakyrelu.(x + collect(Float32, 1:N)))
p, re = Flux.destructure(model)
ps = Flux.params(p)

##
A = diagm(0 => -collect(Float32, 0.0:N), 1 => collect(Float32, 1.0:N))
function ODE(du, u, p, t)
    Dt = 20
    vec = re(p)(u)
    mat = diagm(0 => [-vec; 0.0], -1 => vec)
    G = (A + mat) * Dt
    du[1:N+1] = G * u[1:N+1]
    du[N+2:end] = G * u[N+2:end]
end

u0 = repeat([1.0f0; zeros(Float32, N)], 2)
prob = ODEProblem(ODE, u0, (0.0f0, 20f0), ps[1])
alg = Tsit5()
sol = Array(solve(prob, alg, u0=u0, p=p, saveat=0.0:0.1:20.0))

alg = TRBDF2(autodiff=false);
sense = QuadratureAdjoint(autojacvec=ReverseDiffVJP(true),compile=true)
tsteps = 0:0.1:20.0

function loss_adjoint(p, problem, u0)
    sol = Array(solve(problem, alg, u0=u0, p=p, saveat=tsteps, sensealg=sense))
    return sum(sol)
end

opt = ADAM(0.1)
@time grad = Zygote.gradient(x -> loss_adjoint(x, prob, u0), ps[1])
```

drops all the way down to 

```julia
0.381737 seconds (478.26 k allocations: 367.010 MiB, 16.25% gc time, 11.59% compilation time)
```

In comparison to the ForwardDiff.gradient that was being checked before:

``julia
@time grad = ForwardDiff.gradient(x -> loss_adjoint(x, prob, u0), ps[1])
37.446050 seconds (93.10 M allocations: 31.840 GiB, 8.35% gc time, 12.42% compilation time)
```

that's a 100x acceleration.

The Enzyme issue is a whole separate can of worms so I'll leave that be. But okay, with that fix to the element types I think we can close this as 40 seconds -> 0.4 seconds. Thanks @mohamed82008, now I see what the missing method was trying to say 😅

**Closed by ChrisRackauckas** 2021-11-03 16:57 UTC
