### ISSUE TITLE
Cannot Precompile DifferentialEquations.jl

### ISSUE THREAD

**Issue by smitch151** [SciML/DifferentialEquations.jl#683] opened 2020-10-08 18:46 UTC
Hello, 

When I try to precompile DifferentialEquations.jl I get the following error: 

"ERROR: LoadError: LoadError: UndefVarERror: AbstractADType not defined 
ERROR: LoadError: Faield to precompile ModelingToolkit"

Do you have any suggestions for how to deal with this?

Thank you.

**Comment by Derollez** [comment] 2020-10-08 18:56
Getting the same error with latest tag version

**Comment by smitch151** [comment] 2020-10-08 19:49
I'm using Julia 1.4.0 right now, if that helps

**Comment by ChrisRackauckas** [comment] 2020-10-08 20:06
Looks like we may have had a versioning issue in the latest release. Can you share `]st` ?

**Comment by ChrisRackauckas** [comment] 2020-10-08 20:14
I can't recreate the error locally but I know that it's due to this missing lower bound https://github.com/JuliaRegistries/General/pull/22615 and so we'll get the correct version bound amended into the registry. If you do `]up` the latest versions of the packages should be good though, and installing in a clean environment works, so the issue is more direct to your setup, i.e. there is something that is holding DiffEqBase back (which would be good to fix regardless!).

**Comment by smitch151** [comment] 2020-10-08 20:27
It's still not working for me. I tried ]up and that didn't seem to solve it. Here's my ]st list. 

[7d9fca2a] Arpack v0.4.0
  [6e4b80f9] BenchmarkTools v0.5.0
  [2d3116d5] Bridge v0.11.3
  [336ed68f] CSV v0.7.7
  [052768ef] CUDA v0.1.0
  [be33ccc6] CUDAnative v3.0.4
  [3a865a2d] CuArrays v2.2.2
  [6cf23378] DSGE v1.1.6
  [a93c6f00] DataFrames v0.21.7
  [aae7a2af] DiffEqFlux v1.17.0
  [9fdde737] DiffEqOperators v4.10.0
  [41bf760c] DiffEqSensitivity v6.33.0
  [0c46a032] DifferentialEquations v6.15.0
  [31c24e10] Distributions v0.23.8
  [a3315474] EconPDEs v0.4.0
  [2fe49d83] Expectations v1.6.0
  [587475ba] Flux v0.10.4
  [6e85b7ee] FredData v0.4.0
  [0c68f7d7] GPUArrays v3.4.1
  [28b8d3ca] GR v0.51.0
  [7073ff75] IJulia v1.21.4
  [2fce0c6f] InfinitesimalGenerators v0.3.3
  [c8e1da08] IterTools v1.3.0
  [442fdcdd] Measures v0.3.1
  [e47e5152] ModelConstructors v0.1.12
  [961ee093] ModelingToolkit v3.21.0
  [2774e3e8] NLsolve v4.4.1
  [8faf48c0] NeuralNetDiffEq v1.6.0
  [0af1e411] Opus v1.0.0
  [65888b18] ParameterizedFunctions v5.6.0
  [91a5bcdd] Plots v1.6.10
  [fcd29c91] QuantEcon v0.16.2
  [79098fc4] Rmath v0.6.1
  [c6043b28] SMC v0.1.11
  [00bf1f32] SolveDSGE v0.3.9
  [261fd431] StateSpaceRoutines v0.3.3
  [f3b207a7] StatsPlots v0.14.13
  [789caeaf] StochasticDiffEq v6.25.0
  [34f15cae] StructJuMP v0.2.0
  [c3572dad] Sundials v4.2.6
  [bd369af6] Tables v1.1.0
  [9f7883ad] Tracker v0.2.12
  [e88e6eb3] Zygote v0.4.22
  [8ba89e20] Distributed 
  [37e2e46d] LinearAlgebra 
  [10745b16] Statistics 
  [8dfed614] Test

**Comment by ChrisRackauckas** [comment] 2020-10-08 20:28
Hmm, can I get `]st -m`?

**Comment by smitch151** [comment] 2020-10-08 20:33
Here it is: 

[c3fe647b] AbstractAlgebra v0.10.0
  [621f4979] AbstractFFTs v0.5.0
  [1520ce14] AbstractTrees v0.3.3
  [79e6a3ab] Adapt v1.1.0
  [ec485272] ArnoldiMethod v0.0.4
  [7d9fca2a] Arpack v0.4.0
  [68821587] Arpack_jll v3.5.0+3
  [4fba245c] ArrayInterface v2.13.3
  [4c555306] ArrayLayouts v0.1.5
  [13072b0f] AxisAlgorithms v1.0.0
  [aae01518] BandedMatrices v0.14.3
  [6e4b80f9] BenchmarkTools v0.5.0
  [b99e7846] BinaryProvider v0.5.10
  [a134a8b2] BlackBoxOptim v0.5.0
  [8e7c35d0] BlockArrays v0.11.2
  [ffab5731] BlockBandedMatrices v0.7.2
  [a74b3585] Blosc v0.7.0
  [0b7ba130] Blosc_jll v1.14.3+1
  [764a87c0] BoundaryValueDiffEq v2.5.0
  [2d3116d5] Bridge v0.11.3
  [e1450e63] BufferedStreams v1.0.0
  [6e34b625] Bzip2_jll v1.0.6+4
  [fa961155] CEnum v0.2.0
  [a9c8d775] CPUTime v1.0.0
  [336ed68f] CSV v0.7.7
  [052768ef] CUDA v0.1.0
  [3895d2a7] CUDAapi v4.0.0
  [c5f51814] CUDAdrv v6.3.0
  [be33ccc6] CUDAnative v3.0.4
  [49dc2e85] Calculus v0.5.1
  [a603d957] CanonicalTraits v0.2.2
  [324d7699] CategoricalArrays v0.8.3
  [082447d4] ChainRules v0.6.5
  [d360d2e6] ChainRulesCore v0.8.1
  [17a596ad] ChebyshevApprox v0.1.1
  [34f1f09b] ClusterManagers v0.4.0
  [aaaa29a8] Clustering v0.14.1
  [da1fd8a2] CodeTracking v1.0.3
  [523fee87] CodecBzip2 v0.7.2
  [944b1d66] CodecZlib v0.7.0
  [35d6a980] ColorSchemes v3.10.1
  [3da002f7] ColorTypes v0.10.9
  [5ae59095] Colors v0.12.4
  [861a8166] Combinatorics v1.0.2
  [bbf7d656] CommonSubexpressions v0.3.0
  [34da2185] Compat v3.19.0
  [e66e0078] CompilerSupportLibraries_jll v0.3.3+0
  [8f4d0f93] Conda v1.4.1
  [88cd18e8] ConsoleProgressMonitor v0.1.2
  [187b0558] ConstructionBase v1.0.0
  [d38c429a] Contour v0.5.5
  [adafc99b] CpuId v0.2.2
  [f68482b8] Cthulhu v1.2.2
  [3a865a2d] CuArrays v2.2.2
  [6cf23378] DSGE v1.1.6
  [717857b8] DSP v0.6.6
  [9a962f9c] DataAPI v1.3.0
  [a93c6f00] DataFrames v0.21.7
  [864edb3b] DataStructures v0.17.20
  [e2d170a0] DataValueInterfaces v1.0.0
  [e7dc6d0d] DataValues v0.4.13
  [bcd4f6db] DelayDiffEq v5.24.1
  [2b5f629d] DiffEqBase v6.44.3
  [459566f4] DiffEqCallbacks v2.13.5
  [01453d9d] DiffEqDiffTools v1.7.0
  [5a0ffddc] DiffEqFinancial v2.4.0
  [aae7a2af] DiffEqFlux v1.17.0
  [c894b116] DiffEqJump v6.10.0
  [77a26b50] DiffEqNoiseProcess v5.4.0
  [9fdde737] DiffEqOperators v4.10.0
  [055956cb] DiffEqPhysics v3.6.0
  [41bf760c] DiffEqSensitivity v6.33.0
  [163ba53b] DiffResults v1.0.2
  [b552c78f] DiffRules v1.0.1
  [0c46a032] DifferentialEquations v6.15.0
  [c619ae07] DimensionalPlotRecipes v1.2.0
  [b4f34e82] Distances v0.9.2
  [31c24e10] Distributions v0.23.8
  [ffbed154] DocStringExtensions v0.8.3
  [5ae413db] EarCut_jll v2.1.5+0
  [a3315474] EconPDEs v0.4.0
  [2fe49d83] Expectations v1.6.0
  [d4d017d3] ExponentialUtilities v1.8.0
  [e2ba6199] ExprTools v0.1.2
  [8f5d6c58] EzXML v1.1.0
  [c87230d0] FFMPEG v0.4.0
  [b22a6f82] FFMPEG_jll v4.3.1+2
  [7a1cc6ca] FFTW v1.2.4
  [f5851436] FFTW_jll v3.3.9+5
  [9aa1b823] FastClosures v0.3.2
  [442a2c76] FastGaussQuadrature v0.4.3
  [5789e2e9] FileIO v1.4.3
  [1a297f60] FillArrays v0.8.14
  [6a86dc24] FiniteDiff v2.7.0
  [53c48c17] FixedPointNumbers v0.8.4
  [587475ba] Flux v0.10.4
  [1eca21be] FoldingTrees v1.0.1
  [59287772] Formatting v0.4.1
  [f6369f11] ForwardDiff v0.10.12
  [6e85b7ee] FredData v0.4.0
  [d7e528f0] FreeType2_jll v2.10.1+4
  [559328eb] FriBidi_jll v1.0.5+5
  [069b7b12] FunctionWrappers v1.1.1
  [0c68f7d7] GPUArrays v3.4.1
  [61eb1bfa] GPUCompiler v0.3.0
  [28b8d3ca] GR v0.51.0
  [d54b0c1a] GaussQuadrature v0.5.4
  [6b9d7cbe] GeneralizedGenerated v0.2.7
  [01680d73] GenericSVD v0.3.0
  [5c1252a2] GeometryBasics v0.3.3
  [4d00f742] GeometryTypes v0.8.3
  [42e2da0e] Grisu v1.0.0
  [f67ccb44] HDF5 v0.13.6
  [0234f1f7] HDF5_jll v1.10.5+6
  [cd3eb016] HTTP v0.8.19
  [7073ff75] IJulia v1.21.4
  [7869d1d1] IRTools v0.4.1
  [615f187c] IfElse v0.1.0
  [2fce0c6f] InfinitesimalGenerators v0.3.3
  [d25df0c9] Inflate v0.1.2
  [83e8ac13] IniFile v0.5.0
  [1d5cc7b8] IntelOpenMP_jll v2018.0.3+0
  [a98d9a8b] Interpolations v0.12.10
  [d8418881] Intervals v1.4.2
  [41ab1584] InvertedIndices v1.0.0
  [c8e1da08] IterTools v1.3.0
  [42fd0dbc] IterativeSolvers v0.8.4
  [82899510] IteratorInterfaceExtensions v1.0.0
  [033835bb] JLD2 v0.1.14
  [682c06a0] JSON v0.21.1
  [7d188eb4] JSONSchema v0.3.2
  [4076af6c] JuMP v0.21.4
  [b14d175d] JuliaVariables v0.2.3
  [e5e0dc1b] Juno v0.8.4
  [5ab0869b] KernelDensity v0.6.1
  [0b1a1467] KrylovKit v0.4.2
  [c1c5ebd0] LAME_jll v3.100.0+2
  [929cbde3] LLVM v1.7.0
  [b964fa9f] LaTeXStrings v1.2.0
  [2ee39098] LabelledArrays v1.3.0
  [23fbe1c1] Latexify v0.14.0
  [a5e1c1ea] LatinHypercubeSampling v1.6.4
  [73f95e8e] LatticeRules v0.0.1
  [5078a376] LazyArrays v0.15.1
  [1d6d02ad] LeftChildRightSiblingTrees v0.1.2
  [dd192d2f] LibVPX_jll v1.9.0+0
  [94ce4f54] Libiconv_jll v1.16.0+6
  [093fc24a] LightGraphs v1.3.3
  [d3d80556] LineSearches v7.1.0
  [e6f89c97] LoggingExtras v0.4.2
  [bdcacae8] LoopVectorization v0.8.26
  [5ced341a] Lz4_jll v1.9.2+2
  [23992714] MAT v0.8.1
  [d00139f3] METIS_jll v5.1.0+4
  [856f044c] MKL_jll v2020.2.254+0
  [d8e11817] MLStyle v0.4.6
  [1914dd2f] MacroTools v0.5.5
  [b8f27783] MathOptInterface v0.9.17
  [fdba3010] MathProgBase v0.7.8
  [a3b82374] MatrixFactorizations v0.3.1
  [739be429] MbedTLS v1.0.2
  [c8ffd9c3] MbedTLS_jll v2.16.8+0
  [442fdcdd] Measures v0.3.1
  [e89f7d12] Media v0.5.0
  [e1d29d7a] Missings v0.4.4
  [78c3b35d] Mocking v0.7.1
  [e47e5152] ModelConstructors v0.1.12
  [961ee093] ModelingToolkit v3.21.0
  [46d2c3a1] MuladdMacro v0.2.2
  [f9640e96] MultiScaleArrays v1.8.1
  [6f286f6a] MultivariateStats v0.7.0
  [d8a4904e] MutableArithmetics v0.2.10
  [d41bc354] NLSolversBase v7.5.0
  [76087f3c] NLopt v0.6.0
  [079eb43e] NLopt_jll v2.6.2+0
  [2774e3e8] NLsolve v4.4.1
  [872c559c] NNlib v0.6.6
  [77ba4419] NaNMath v0.3.4
  [71a1bf82] NameResolution v0.1.5
  [b8a86587] NearestNeighbors v0.4.6
  [8faf48c0] NeuralNetDiffEq v1.6.0
  [4d1e1d77] Nullables v1.0.0
  [510215fc] Observables v0.3.2
  [6fe1bfb0] OffsetArrays v1.3.0
  [796d8c31] Ogg v1.0.0
  [e7412a2a] Ogg_jll v1.3.4+1
  [4536629a] OpenBLAS_jll v0.3.10+0
  [458c3c95] OpenSSL_jll v1.1.1+5
  [efe28fd5] OpenSpecFun_jll v0.5.3+3
  [429524aa] Optim v0.21.0
  [0af1e411] Opus v1.0.0
  [91d4177d] Opus_jll v1.3.1+2
  [bac558e1] OrderedCollections v1.3.1
  [1dea7af3] OrdinaryDiffEq v5.42.3
  [90014a1f] PDMats v0.10.1
  [9b87118b] PackageCompiler v1.2.1
  [774612a8] ParameterJuMP v0.2.0
  [65888b18] ParameterizedFunctions v5.6.0
  [d96e819e] Parameters v0.12.1
  [69de0a69] Parsers v1.0.11
  [fcfa6960] PiecewiseLinearApprox v0.1.1
  [ccf2f8ad] PlotThemes v2.0.0
  [995b91a9] PlotUtils v1.0.7
  [91a5bcdd] Plots v1.6.10
  [e409e4f3] PoissonRandom v0.4.0
  [f27b6e38] Polynomials v0.8.0
  [2dfb63ee] PooledArrays v0.5.3
  [85a6dd25] PositiveFactorizations v0.2.3
  [8162dcfd] PrettyPrint v0.2.0
  [27ebfcd6] Primes v0.5.0
  [33c8b6b6] ProgressLogging v0.1.3
  [92933f4c] ProgressMeter v1.4.0
  [1fd47b50] QuadGK v2.4.1
  [fcd29c91] QuantEcon v0.16.2
  [8a4e6c94] QuasiMonteCarlo v0.2.1
  [e6cf234a] RandomNumbers v1.4.0
  [c84ed2f1] Ratios v0.4.0
  [3cdcf5f2] RecipesBase v1.1.0
  [01d81517] RecipesPipeline v0.1.13
  [731186ca] RecursiveArrayTools v2.7.1
  [f2c3362d] RecursiveFactorization v0.1.4
  [189a3867] Reexport v0.2.0
  [ae029012] Requires v1.1.0
  [ae5879a3] ResettableStacks v1.0.0
  [37e2e3b7] ReverseDiff v1.4.3
  [79098fc4] Rmath v0.6.1
  [f50d1b31] Rmath_jll v0.2.2+1
  [f2b01f46] Roots v1.0.5
  [21efa798] SIMDPirates v0.8.25
  [476501e8] SLEEFPirates v0.5.5
  [c6043b28] SMC v0.1.11
  [1bc83da4] SafeTestsets v0.0.1
  [91c51154] SentinelArrays v1.2.16
  [992d4aef] Showoff v0.3.2
  [699a6c99] SimpleTraits v0.9.3
  [6b19cf85] SmolyakApprox v0.1.1
  [ed01d8cd] Sobol v1.4.0
  [b85f4697] SoftGlobalScope v1.1.0
  [00bf1f32] SolveDSGE v0.3.9
  [a2af1166] SortingAlgorithms v0.3.1
  [47a9eef4] SparseDiffTools v1.10.0
  [d4ead438] SpatialIndexing v0.1.2
  [276daf66] SpecialFunctions v0.10.3
  [261fd431] StateSpaceRoutines v0.3.3
  [90137ffa] StaticArrays v0.12.4
  [2913bbd2] StatsBase v0.33.2
  [4c63d2b9] StatsFuns v0.9.5
  [f3b207a7] StatsPlots v0.14.13
  [9672c7b4] SteadyStateDiffEq v1.5.1
  [789caeaf] StochasticDiffEq v6.25.0
  [09ab397b] StructArrays v0.4.4
  [34f15cae] StructJuMP v0.2.0
  [856f2bd8] StructTypes v1.1.0
  [bea87d4a] SuiteSparse_jll v5.4.0+9
  [c3572dad] Sundials v4.2.6
  [fb77eaff] Sundials_jll v5.2.0+1
  [d1185830] SymbolicUtils v0.5.1
  [ab02a1b2] TableOperations v0.2.1
  [3783bdb8] TableTraits v1.0.0
  [bd369af6] Tables v1.1.0
  [5d786b92] TerminalLoggers v0.1.2
  [f269a46b] TimeZones v1.4.0
  [a759f4b9] TimerOutputs v0.5.6
  [9f7883ad] Tracker v0.2.12
  [2c80a279] Trajectories v0.2.2
  [3bb67fe8] TranscodingStreams v0.9.5
  [a2a6695c] TreeViews v0.3.0
  [3a884ed6] UnPack v1.0.2
  [1986cc42] Unitful v1.4.1
  [3d5dd08c] VectorizationBase v0.12.33
  [81def892] VersionParsing v1.2.0
  [19fa3120] VertexSafeGraphs v0.1.2
  [cc8bc4a8] Widgets v0.6.2
  [efce3f68] WoodburyMatrices v0.5.2
  [02c8fc9c] XML2_jll v2.9.10+2
  [c2297ded] ZMQ v1.2.1
  [8f1865be] ZeroMQ_jll v4.3.2+4
  [a5390f91] ZipFile v0.9.2
  [83775a58] Zlib_jll v1.2.11+16
  [3161d3a3] Zstd_jll v1.4.5+1
  [e88e6eb3] Zygote v0.4.22
  [700de1a5] ZygoteRules v0.2.0
  [0ac62f75] libass_jll v0.14.0+3
  [f638f0a6] libfdk_aac_jll v0.1.6+3
  [f27f6e37] libvorbis_jll v1.3.6+5
  [1270edf5] x264_jll v2020.7.14+1
  [dfaa095f] x265_jll v3.0.0+2
  [2a0f44e3] Base64 
  [ade2ca70] Dates 
  [8bb1440f] DelimitedFiles 
  [8ba89e20] Distributed 
  [7b1f6079] FileWatching 
  [9fa8497b] Future 
  [b77e0a4c] InteractiveUtils 
  [76f85450] LibGit2 
  [8f399da3] Libdl 
  [37e2e46d] LinearAlgebra 
  [56ddb016] Logging 
  [d6f4376e] Markdown 
  [a63ad114] Mmap 
  [44cfe95a] Pkg 
  [de0858da] Printf 
  [9abbd945] Profile 
  [3fa0cd96] REPL 
  [9a3f8284] Random 
  [ea8e919c] SHA 
  [9e88b42a] Serialization 
  [1a1011a3] SharedArrays 
  [6462fe0b] Sockets 
  [2f01184e] SparseArrays 
  [10745b16] Statistics 
  [4607b0f0] SuiteSparse 
  [8dfed614] Test 
  [cf7118a7] UUIDs 
  [4ec0a83e] Unicode

**Comment by ChrisRackauckas** [comment] 2020-10-08 20:42
If you do `]add DiffEqBase@6.48` what happens?

**Comment by smitch151** [comment] 2020-10-08 20:44
That seems to conflict with DataStructures and  CUDA

**Comment by ChrisRackauckas** [comment] 2020-10-08 20:48
Oh yes, the later versions of DiffEqBase want DataStructures v0.18 which is what's keeping it back. So the ModelingToolkit bound will fix this by just not giving you the latest version, but the real offender here is whatever other package has an upper bound on the core DataStructures library... that just is going to cause issues. It's interesting you're on CUDA 0.1 though: is that by choice? CUDA.jl released its 2.0, which should work fine here.

**Comment by ChrisRackauckas** [comment] 2020-10-08 20:50
JuMP v0.21.4 also has such a bound and should be v0.21.5. This is all saying that there's something deeper in your system that is causing CUDA, JuMP, DiffEqBase, etc. to all be held back.

**Comment by ChrisRackauckas** [comment] 2020-10-08 20:52
Oh:

```julia
[3a865a2d] CuArrays v2.2.2
[8faf48c0] NeuralNetDiffEq v1.6.0
```

You might want to remove those, since those were renamed CUDA.jl and NeuralPDE.jl respectively, and those old versions may be causing your issue.

**Comment by smitch151** [comment] 2020-10-08 21:06
Thank you very much! Is there a good way to identify what packages have upper bounds on other packages?

**Comment by ChrisRackauckas** [comment] 2020-10-09 01:56
🤷 Add and find out. At this point I just follow a few thousand packages and tend to know, but that's obviously not a scalable solution. Take that to the Discourse though: for now, I'm closing this since the precompilation issue is fixed by appropriate version bounding:

https://github.com/JuliaRegistries/General/pull/22615#issuecomment-705921003

**Closed by ChrisRackauckas** 2020-10-09 01:56 UTC
